//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Multilang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Multilang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Photizer.Multilang", typeof(Multilang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddDataDialog_Add {
            get {
                return ResourceManager.GetString("AddDataDialog.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish/Cancel.
        /// </summary>
        public static string AddDataDialog_FinishCancel {
            get {
                return ResourceManager.GetString("AddDataDialog.FinishCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string AddNewCameraDialog_Camera {
            get {
                return ResourceManager.GetString("AddNewCameraDialog.Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is empty.
        /// </summary>
        public static string AddNewCameraDialog_CameraIsEmpty {
            get {
                return ResourceManager.GetString("AddNewCameraDialog.CameraIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Camera added.
        /// </summary>
        public static string AddNewCameraDialog_NewCameraAdded {
            get {
                return ResourceManager.GetString("AddNewCameraDialog.NewCameraAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string AddNewCategoryDialog_Category {
            get {
                return ResourceManager.GetString("AddNewCategoryDialog.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is empty.
        /// </summary>
        public static string AddNewCategoryDialog_CategoryIsEmpty {
            get {
                return ResourceManager.GetString("AddNewCategoryDialog.CategoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category added.
        /// </summary>
        public static string AddNewCategoryDialog_NewCategoryAdded {
            get {
                return ResourceManager.GetString("AddNewCategoryDialog.NewCategoryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Name.
        /// </summary>
        public static string AddNewCollectionDialog_CollectionName {
            get {
                return ResourceManager.GetString("AddNewCollectionDialog.CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Name is empty.
        /// </summary>
        public static string AddNewCollectionDialog_CollectionNameIsEmpty {
            get {
                return ResourceManager.GetString("AddNewCollectionDialog.CollectionNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Collection added.
        /// </summary>
        public static string AddNewCollectionDialog_NewCollectionAdded {
            get {
                return ResourceManager.GetString("AddNewCollectionDialog.NewCollectionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lense.
        /// </summary>
        public static string AddNewLenseDialog_Lense {
            get {
                return ResourceManager.GetString("AddNewLenseDialog.Lense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lense is empty.
        /// </summary>
        public static string AddNewLenseDialog_LenseIsEmpty {
            get {
                return ResourceManager.GetString("AddNewLenseDialog.LenseIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lense added.
        /// </summary>
        public static string AddNewLenseDialog_NewLenseAdded {
            get {
                return ResourceManager.GetString("AddNewLenseDialog.NewLenseAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddNewLocationDialog_Country {
            get {
                return ResourceManager.GetString("AddNewLocationDialog.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is empty.
        /// </summary>
        public static string AddNewLocationDialog_CountryIsEmpty {
            get {
                return ResourceManager.GetString("AddNewLocationDialog.CountryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude and Latitude have to be set later in the Settings Menu.
        /// </summary>
        public static string AddNewLocationDialog_Info {
            get {
                return ResourceManager.GetString("AddNewLocationDialog.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Location added.
        /// </summary>
        public static string AddNewLocationDialog_NewLocationAdded {
            get {
                return ResourceManager.GetString("AddNewLocationDialog.NewLocationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string AddNewLocationDialog_Place {
            get {
                return ResourceManager.GetString("AddNewLocationDialog.Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place is empty.
        /// </summary>
        public static string AddNewLocationDialog_PlaceIsEmpty {
            get {
                return ResourceManager.GetString("AddNewLocationDialog.PlaceIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string AddNewPersonDialog_Firstname {
            get {
                return ResourceManager.GetString("AddNewPersonDialog.Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname is empty.
        /// </summary>
        public static string AddNewPersonDialog_FirstnameIsEmpty {
            get {
                return ResourceManager.GetString("AddNewPersonDialog.FirstnameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string AddNewPersonDialog_Lastname {
            get {
                return ResourceManager.GetString("AddNewPersonDialog.Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname is empty.
        /// </summary>
        public static string AddNewPersonDialog_LastnameIsEmpty {
            get {
                return ResourceManager.GetString("AddNewPersonDialog.LastnameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Person added.
        /// </summary>
        public static string AddNewPersonDialog_NewPersonAdded {
            get {
                return ResourceManager.GetString("AddNewPersonDialog.NewPersonAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tag added.
        /// </summary>
        public static string AddNewTagDialog_NewTagAdded {
            get {
                return ResourceManager.GetString("AddNewTagDialog.NewTagAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string AddNewTagDialog_Tag {
            get {
                return ResourceManager.GetString("AddNewTagDialog.Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag is empty.
        /// </summary>
        public static string AddNewTagDialog_TagIsEmpty {
            get {
                return ResourceManager.GetString("AddNewTagDialog.TagIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Person.
        /// </summary>
        public static string AddPicture_AddPerson {
            get {
                return ResourceManager.GetString("AddPicture.AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string AddPicture_CreatedDate {
            get {
                return ResourceManager.GetString("AddPicture.CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time.
        /// </summary>
        public static string AddPicture_CreatedTime {
            get {
                return ResourceManager.GetString("AddPicture.CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Location.
        /// </summary>
        public static string AddPicture_CreateNewLocation {
            get {
                return ResourceManager.GetString("AddPicture.CreateNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Person.
        /// </summary>
        public static string AddPicture_CreateNewPerson {
            get {
                return ResourceManager.GetString("AddPicture.CreateNewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string AddPicture_Rating {
            get {
                return ResourceManager.GetString("AddPicture.Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AddPicture_Save {
            get {
                return ResourceManager.GetString("AddPicture.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string AddPicture_SelectCountry {
            get {
                return ResourceManager.GetString("AddPicture.SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Images.
        /// </summary>
        public static string AddPicture_SelectImages {
            get {
                return ResourceManager.GetString("AddPicture.SelectImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or Add Camera.
        /// </summary>
        public static string AddPicture_SelectOrAddCamera {
            get {
                return ResourceManager.GetString("AddPicture.SelectOrAddCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or Add Category.
        /// </summary>
        public static string AddPicture_SelectOrAddCategory {
            get {
                return ResourceManager.GetString("AddPicture.SelectOrAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or Add Lense.
        /// </summary>
        public static string AddPicture_SelectOrAddLense {
            get {
                return ResourceManager.GetString("AddPicture.SelectOrAddLense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or Add Tag.
        /// </summary>
        public static string AddPicture_SelectOrAddTag {
            get {
                return ResourceManager.GetString("AddPicture.SelectOrAddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Person.
        /// </summary>
        public static string AddPicture_SelectPerson {
            get {
                return ResourceManager.GetString("AddPicture.SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Place.
        /// </summary>
        public static string AddPicture_SelectPlace {
            get {
                return ResourceManager.GetString("AddPicture.SelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AddPicture_Settings {
            get {
                return ResourceManager.GetString("AddPicture.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AddPicture_Title {
            get {
                return ResourceManager.GetString("AddPicture.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Picture Settings.
        /// </summary>
        public static string AddPictureSettingsDialog_AddPictureSettings {
            get {
                return ResourceManager.GetString("AddPictureSettingsDialog.AddPictureSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string AddPictureSettingsDialog_Apply {
            get {
                return ResourceManager.GetString("AddPictureSettingsDialog.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Category.
        /// </summary>
        public static string AddPictureSettingsDialog_KeepCategory {
            get {
                return ResourceManager.GetString("AddPictureSettingsDialog.KeepCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep　Location.
        /// </summary>
        public static string AddPictureSettingsDialog_KeepLocation {
            get {
                return ResourceManager.GetString("AddPictureSettingsDialog.KeepLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeepPeople.
        /// </summary>
        public static string AddPictureSettingsDialog_KeepPeople {
            get {
                return ResourceManager.GetString("AddPictureSettingsDialog.KeepPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Tags.
        /// </summary>
        public static string AddPictureSettingsDialog_KeepTags {
            get {
                return ResourceManager.GetString("AddPictureSettingsDialog.KeepTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Import/Export.
        /// </summary>
        public static string AppSettings_DatabaseImportExport {
            get {
                return ResourceManager.GetString("AppSettings.DatabaseImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Settings.
        /// </summary>
        public static string AppSettings_FolderSettings {
            get {
                return ResourceManager.GetString("AppSettings.FolderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Collections.
        /// </summary>
        public static string CollectionsDetail_BackToCollections {
            get {
                return ResourceManager.GetString("CollectionsDetail.BackToCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Folder.
        /// </summary>
        public static string CollectionsDetail_ExportToFolder {
            get {
                return ResourceManager.GetString("CollectionsDetail.ExportToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures per Page.
        /// </summary>
        public static string CollectionsDetail_PictuersPerPage {
            get {
                return ResourceManager.GetString("CollectionsDetail.PictuersPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string DatabaseImportExport_Export {
            get {
                return ResourceManager.GetString("DatabaseImportExport.Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string DatabaseImportExport_Import {
            get {
                return ResourceManager.GetString("DatabaseImportExport.Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photizer&apos;s Data is stored in a Database file called &apos;Photizer.db&apos; in the Photizer&apos;s AppData folder:
        ///   CurrentUser/AppData/Local/PhotizerData
        ///Every time the application is closed Photizer will automatically create a Backup in the /DatabaseBackup folder..
        /// </summary>
        public static string DatabaseImportExport_InfoOne {
            get {
                return ResourceManager.GetString("DatabaseImportExport.InfoOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To replace the current database with a backup you first have to close the Photizer App. 
        ///Then copy the database file from the backup folder into the &apos;Photizer&apos; folder and replace the &apos;Photizer.db&apos; file.
        ///The &apos;Import&apos; button opens both folders..
        /// </summary>
        public static string DatabaseImportExport_InfoThree {
            get {
                return ResourceManager.GetString("DatabaseImportExport.InfoThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Export&apos; will do a manual copy of the database into the backup folder..
        /// </summary>
        public static string DatabaseImportExport_InfoTwo {
            get {
                return ResourceManager.GetString("DatabaseImportExport.InfoTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string DetailEdit_AddTag {
            get {
                return ResourceManager.GetString("DetailEdit.AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DetailEdit_Cancel {
            get {
                return ResourceManager.GetString("DetailEdit.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Camera.
        /// </summary>
        public static string DetailEdit_SelectCamera {
            get {
                return ResourceManager.GetString("DetailEdit.SelectCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string DetailEdit_SelectCategory {
            get {
                return ResourceManager.GetString("DetailEdit.SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lense.
        /// </summary>
        public static string DetailEdit_SelectLense {
            get {
                return ResourceManager.GetString("DetailEdit.SelectLense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tag.
        /// </summary>
        public static string DetailEdit_SelectTag {
            get {
                return ResourceManager.GetString("DetailEdit.SelectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EditCamerasData_Header {
            get {
                return ResourceManager.GetString("EditCamerasData.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EditCategoriesData_Header {
            get {
                return ResourceManager.GetString("EditCategoriesData.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cameras.
        /// </summary>
        public static string EditData_EditCameras {
            get {
                return ResourceManager.GetString("EditData.EditCameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Categories.
        /// </summary>
        public static string EditData_EditCategories {
            get {
                return ResourceManager.GetString("EditData.EditCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Lenses.
        /// </summary>
        public static string EditData_EditLenses {
            get {
                return ResourceManager.GetString("EditData.EditLenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Locations.
        /// </summary>
        public static string EditData_EditLocations {
            get {
                return ResourceManager.GetString("EditData.EditLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit People.
        /// </summary>
        public static string EditData_EditPeople {
            get {
                return ResourceManager.GetString("EditData.EditPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tags.
        /// </summary>
        public static string EditData_EditTags {
            get {
                return ResourceManager.GetString("EditData.EditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EditLensesData_Header {
            get {
                return ResourceManager.GetString("EditLensesData.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string EditLocationData_HeaderCountry {
            get {
                return ResourceManager.GetString("EditLocationData.HeaderCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string EditLocationData_HeaderLatitude {
            get {
                return ResourceManager.GetString("EditLocationData.HeaderLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string EditLocationData_HeaderLocation {
            get {
                return ResourceManager.GetString("EditLocationData.HeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string EditLocationData_HeaderLongitude {
            get {
                return ResourceManager.GetString("EditLocationData.HeaderLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string EditPeopleData_HeaderFirstName {
            get {
                return ResourceManager.GetString("EditPeopleData.HeaderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string EditPeopleData_HeaderLastName {
            get {
                return ResourceManager.GetString("EditPeopleData.HeaderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string EditTagsData_Header {
            get {
                return ResourceManager.GetString("EditTagsData.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can use Photizer you have to select a Main and Backup Folder where the pictures will be saved to! When a picture is added to Photizer one file will be created in the Main folder and a Copy in the Backup folder.
        /// </summary>
        public static string FolderSettings_Info {
            get {
                return ResourceManager.GetString("FolderSettings.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Backup Folder.
        /// </summary>
        public static string FolderSettings_SelectBackupFolder {
            get {
                return ResourceManager.GetString("FolderSettings.SelectBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Main Folder.
        /// </summary>
        public static string FolderSettings_SelectMainFolder {
            get {
                return ResourceManager.GetString("FolderSettings.SelectMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string GeocodingDialog_Close {
            get {
                return ResourceManager.GetString("GeocodingDialog.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found or no Internet connection available.
        /// </summary>
        public static string GeocodingDialog_Error {
            get {
                return ResourceManager.GetString("GeocodingDialog.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string GeocodingDialog_Latitude {
            get {
                return ResourceManager.GetString("GeocodingDialog.Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string GeocodingDialog_Longitude {
            get {
                return ResourceManager.GetString("GeocodingDialog.Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Coordinates.
        /// </summary>
        public static string GeocodingDialog_SaveCoordinates {
            get {
                return ResourceManager.GetString("GeocodingDialog.SaveCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Coordinates.
        /// </summary>
        public static string GeocodingDialog_UpdatedCoordinates {
            get {
                return ResourceManager.GetString("GeocodingDialog.UpdatedCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photos.
        /// </summary>
        public static string MainMenu_AddPictures {
            get {
                return ResourceManager.GetString("MainMenu.AddPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string MainMenu_Collections {
            get {
                return ResourceManager.GetString("MainMenu.Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data.
        /// </summary>
        public static string MainMenu_EditData {
            get {
                return ResourceManager.GetString("MainMenu.EditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string MainMenu_Map {
            get {
                return ResourceManager.GetString("MainMenu.Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Overview.
        /// </summary>
        public static string MainMenu_Pictures {
            get {
                return ResourceManager.GetString("MainMenu.Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainMenu_Settings {
            get {
                return ResourceManager.GetString("MainMenu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version available, do you want to update now?.
        /// </summary>
        public static string PhotizerUpdateNotification {
            get {
                return ResourceManager.GetString("PhotizerUpdateNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting Updater:.
        /// </summary>
        public static string PhotizerUpdaterError {
            get {
                return ResourceManager.GetString("PhotizerUpdaterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available but Photizer.Updater.exe not found!.
        /// </summary>
        public static string PhotizerUpdaterNotFound {
            get {
                return ResourceManager.GetString("PhotizerUpdaterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string PictureDetail_GoBack {
            get {
                return ResourceManager.GetString("PictureDetail.GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Edit.
        /// </summary>
        public static string PictureDetail_ToggleEdit {
            get {
                return ResourceManager.GetString("PictureDetail.ToggleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date ascending.
        /// </summary>
        public static string ResultSortCategory_CreatedDateAscending {
            get {
                return ResourceManager.GetString("ResultSortCategory.CreatedDateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date descending.
        /// </summary>
        public static string ResultSortCategory_CreatedDateDescending {
            get {
                return ResourceManager.GetString("ResultSortCategory.CreatedDateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added ascending.
        /// </summary>
        public static string ResultSortCategory_PhotizerAddedAscending {
            get {
                return ResourceManager.GetString("ResultSortCategory.PhotizerAddedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added descending.
        /// </summary>
        public static string ResultSortCategory_PhotizerAddedDescending {
            get {
                return ResourceManager.GetString("ResultSortCategory.PhotizerAddedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating ascending.
        /// </summary>
        public static string ResultSortCategory_RatingAscending {
            get {
                return ResourceManager.GetString("ResultSortCategory.RatingAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating descending.
        /// </summary>
        public static string ResultSortCategory_RatingDescending {
            get {
                return ResourceManager.GetString("ResultSortCategory.RatingDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Place.
        /// </summary>
        public static string SearchParamater_SelectPlace {
            get {
                return ResourceManager.GetString("SearchParamater.SelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Person.
        /// </summary>
        public static string SearchParameter_AddPerson {
            get {
                return ResourceManager.GetString("SearchParameter.AddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string SearchParameter_AddTag {
            get {
                return ResourceManager.GetString("SearchParameter.AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date from.
        /// </summary>
        public static string SearchParameter_CreatedDateFrom {
            get {
                return ResourceManager.GetString("SearchParameter.CreatedDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date to.
        /// </summary>
        public static string SearchParameter_CreatedDateTo {
            get {
                return ResourceManager.GetString("SearchParameter.CreatedDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time from.
        /// </summary>
        public static string SearchParameter_CreatedTimeFrom {
            get {
                return ResourceManager.GetString("SearchParameter.CreatedTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Time to.
        /// </summary>
        public static string SearchParameter_CreatedTimeTo {
            get {
                return ResourceManager.GetString("SearchParameter.CreatedTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Title.
        /// </summary>
        public static string SearchParameter_PictureTitle {
            get {
                return ResourceManager.GetString("SearchParameter.PictureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Parameters.
        /// </summary>
        public static string SearchParameter_SearchParameters {
            get {
                return ResourceManager.GetString("SearchParameter.SearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Camera.
        /// </summary>
        public static string SearchParameter_SelectCamera {
            get {
                return ResourceManager.GetString("SearchParameter.SelectCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SearchParameter_SelectCategory {
            get {
                return ResourceManager.GetString("SearchParameter.SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SearchParameter_SelectCountry {
            get {
                return ResourceManager.GetString("SearchParameter.SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lense.
        /// </summary>
        public static string SearchParameter_SelectLense {
            get {
                return ResourceManager.GetString("SearchParameter.SelectLense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Person.
        /// </summary>
        public static string SearchParameter_SelectPerson {
            get {
                return ResourceManager.GetString("SearchParameter.SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tag.
        /// </summary>
        public static string SearchParameter_SelectTag {
            get {
                return ResourceManager.GetString("SearchParameter.SelectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Collection.
        /// </summary>
        public static string SearchResult_AddToCollection {
            get {
                return ResourceManager.GetString("SearchResult.AddToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Folder.
        /// </summary>
        public static string SearchResult_ExportToFolder {
            get {
                return ResourceManager.GetString("SearchResult.ExportToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures per Page.
        /// </summary>
        public static string SearchResult_PicturesPerPage {
            get {
                return ResourceManager.GetString("SearchResult.PicturesPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Collection.
        /// </summary>
        public static string SearchResult_SelectCollection {
            get {
                return ResourceManager.GetString("SearchResult.SelectCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Result by.
        /// </summary>
        public static string SearchResult_SortResultBy {
            get {
                return ResourceManager.GetString("SearchResult.SortResultBy", resourceCulture);
            }
        }
    }
}
